# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 02:36
from __future__ import unicode_literals

import apps.cards.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('attribution_instructions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CardBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('image', models.ImageField(upload_to='cards/backgrounds/')),
                ('has_art', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cards.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('level', models.PositiveSmallIntegerField(blank=True, help_text='Only used for creatures (and items?)', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.cards.models.card_image_path)),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_approved', to=settings.AUTH_USER_MODEL)),
                ('artist', models.ForeignKey(blank=True, help_text='Required if an image is uploaded.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Artist')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='cards.Card')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_submitted', to=settings.AUTH_USER_MODEL)),
                ('rejector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_rejected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'approved_at',
                'ordering': ('-approved_at',),
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardBackground')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(upload_to='decks/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Rulebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('download', models.FileField(upload_to='rules/downloads/')),
            ],
        ),
        migrations.CreateModel(
            name='StatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='cards/stats/icons/')),
            ],
        ),
        migrations.AddField(
            model_name='cardrevision',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.CardType'),
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ManyToManyField(blank=True, related_name='cards', to='cards.Deck'),
        ),
    ]
