# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrevision',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cardrevision',
            name='rejector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards_rejected', to=settings.AUTH_USER_MODEL),
        ),
    ]
