# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:25
from __future__ import unicode_literals

import apps.cards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20160330_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.cards.models.card_image_path)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Artist')),
            ],
        ),
        migrations.RemoveField(
            model_name='cardrevision',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='cardrevision',
            name='image',
        ),
        migrations.AddField(
            model_name='cardrevision',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.CardArt'),
        ),
    ]
