# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 03:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20160330_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrevision',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cardrevision',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
