# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20160404_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbackground',
            name='image',
            field=models.FileField(upload_to='cards/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='icon',
            field=models.FileField(upload_to='decks/icons/'),
        ),
        migrations.AlterField(
            model_name='stattype',
            name='image',
            field=models.FileField(upload_to='cards/stats/icons/'),
        ),
    ]
