# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 04:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20160404_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrevision',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
    ]
