# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20160404_0423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardcomment',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='cardrevision',
            options={'get_latest_by': 'approved_at', 'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='cardcomment',
            name='text',
            field=models.TextField(),
        ),
    ]
